      PARAMETER (KBMAX=1001)
      REAL KAPPA,KN,KM,KH,KQ,L0,L,KM0 
C
      COMMON/BLKT/TF(KBMAX),T(KBMAX),TB(KBMAX),SF(KBMAX),S(KBMAX),
     1     SB(KBMAX)
      COMMON/BLKU/UF(KBMAX),U(KBMAX),UB(KBMAX),VF(KBMAX),V(KBMAX),
     1     VB(KBMAX)

      COMMON/BLKWU/WUSURF,WVSURF,WUBOT,WVBOT

      COMMON/BLKZ/Z(KBMAX),ZZ(KBMAX),DZ(KBMAX),DZZ(KBMAX),UMOL
      COMMON/BLKH/H,D
      COMMON/BLKK/KM(KBMAX)
C 
C    WORK ARRAYS
C
      COMMON/BLKA/A(KBMAX),C(KBMAX),EE(KBMAX),GG(KBMAX)


